name = "forest"
tasks_title = "♣ Tasks"
details_title = "⌁ Details"
project_icon = "◆ "
section_icon = "  └ "
task_icon = "  ∙ "
help_separator = "◇"
notice_title = "❧ Notice"
error_title = "⚠ Error"
confirm_title = "⌘ Confirm"
list_border = "green"
detail_border = "light_green"
label = "light_green"
project_icon_color = "yellow"
project = "light_green"
section_icon_color = "green"
section = "yellow"
task = "white"
description = "dark_gray"
selected_bg = "green"
selected_fg = "black"
status = "light_green"
age_fresh = "light_green"
age_aging = "yellow"
age_old = "light_red"
info = "light_green"
error = "light_red"
confirm = "yellow"
