name = "midnight"
tasks_title = "☾ Tasks"
details_title = "✧ Details"
project_icon = "★ "
section_icon = "  ┆ "
task_icon = "  ⋅ "
help_separator = "⋆"
notice_title = "☄ Notice"
error_title = "× Error"
confirm_title = "☽ Confirm"
list_border = "dark_gray"
detail_border = "light_blue"
label = "light_magenta"
project_icon_color = "light_blue"
project = "light_blue"
section_icon_color = "dark_gray"
section = "light_magenta"
task = "gray"
description = "dark_gray"
selected_bg = "dark_gray"
selected_fg = "white"
status = "gray"
age_fresh = "light_blue"
age_aging = "light_magenta"
age_old = "light_red"
info = "light_blue"
error = "light_red"
confirm = "light_magenta"
