name = "ocean"
tasks_title = "≈ Tasks"
details_title = "≋ Details"
project_icon = "◈ "
section_icon = "  ╭ "
task_icon = "  ○ "
help_separator = "~"
notice_title = "≃ Notice"
error_title = "⚓ Error"
confirm_title = "◌ Confirm"
list_border = "cyan"
detail_border = "blue"
label = "light_cyan"
project_icon_color = "light_blue"
project = "light_cyan"
section_icon_color = "cyan"
section = "light_blue"
task = "white"
description = "cyan"
selected_bg = "cyan"
selected_fg = "black"
status = "light_cyan"
age_fresh = "light_cyan"
age_aging = "light_blue"
age_old = "magenta"
info = "light_cyan"
error = "light_red"
confirm = "light_blue"
