name = "sunset"
tasks_title = "☀ Tasks"
details_title = "✺ Details"
project_icon = "◉ "
section_icon = "  ╰ "
task_icon = "  ◦ "
help_separator = "✦"
notice_title = "✹ Notice"
error_title = "‼ Error"
confirm_title = "✷ Confirm"
list_border = "light_red"
detail_border = "light_magenta"
label = "yellow"
project_icon_color = "yellow"
project = "light_red"
section_icon_color = "light_red"
section = "light_magenta"
task = "white"
description = "light_red"
selected_bg = "light_magenta"
selected_fg = "black"
status = "yellow"
age_fresh = "cyan"
age_aging = "yellow"
age_old = "light_red"
info = "yellow"
error = "light_red"
confirm = "light_red"
